function net = continue_train( ...
    layers, ...
    train_size, ...
    XTrain, ...
    YTrain, ...
    XValidation, ...
    YValidation)
miniBatchSize  = 128;
validationFrequency = floor(train_size/miniBatchSize);
options = trainingOptions('sgdm', ...
    'MiniBatchSize',miniBatchSize, ...
    'MaxEpochs',15, ...
    'InitialLearnRate',1e-5, ...
    'LearnRateDropPeriod',2, ...
    'LearnRateDropFactor',0.3,...
    'LearnRateSchedule','piecewise', ...
    'Shuffle','every-epoch', ...
    'ValidationData',{XValidation,YValidation}, ...
    'ValidationFrequency',validationFrequency, ...
    'Plots','training-progress', ...
    'Verbose',false, ...
    'OutputNetwork','best-validation-loss', ...
    'CheckpointPath','./checkpoints');

net = trainNetwork(XTrain,YTrain,layers,options);
end